version: '2'
services:
  zookeeper:
    image: apache-zookeeper/ver:3.4.9
    container_name: zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
  cassandra:
    image: luketillman/datastax-enterprise:5.0.6
    container_name: cassandra
    ports:
      - "9042"
    volumes:
      - /Docker/Volumes/Cassandra:/var/lib/cassandra
      - /Docker/Volumes/Cassandra/Logs:/var/log/cassandra
  spark-master:
    image: bde2020/spark-master:2.0.0-hadoop2.7-hive-java8
    container_name: spark-master
    ports: 
      - "8080:8080"
      - "7077:7077"
    environment:
      ENABLE_INIT_DAEMON: "false"
  spark-slave:
    image: bde2020/spark-master:2.0.0-hadoop2.7-hive-java8
    container_name: spark-slave
    ports: 
      - "8081:8080"
      - "7078:7077"
    environment:
      ENABLE_INIT_DAEMON: "false"
    links:
      - spark-master:spark-master
  kafka:
    image: apache-kafka/ver:0.10.0.2
    container_name: kafka
    depends_on:
      - zookeeper
      - cassandra
      - spark-master
      - spark-slave
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "vplusTopic:1:1"
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms128M"
    volumes:  
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - zookeeper:zookeeper
      - cassandra:cassandra
      - spark-master
      - spark-slave
  namenode:
    image: bde2020/hadoop-namenode:1.1.0-hadoop2.7.1-java8
    container_name: namenode
    volumes:
      - /Docker/Volumes/Hdfs/namenode:/hadoop/dfs/name
    environment:
      CLUSTER_NAME: test
    env_file:
      - docker-hadoop/hadoop.env
    ports: 
      - "50070:50070"
      - "8020:8020"
  resourcemanager:
    image: bde2020/hadoop-resourcemanager:1.1.0-hadoop2.7.1-java8
    container_name: resourcemanager
    depends_on:
      - namenode
      - datanode1
    env_file:
      - docker-hadoop/hadoop.env
    ports:
      - "8088:8088"
  
  historyserver:
    image: bde2020/hadoop-historyserver:1.1.0-hadoop2.7.1-java8
    container_name: historyserver
    depends_on:
      - namenode
      - datanode1
    volumes:
      - /Docker/Volumes/Hdfs/historyserver:/hadoop/yarn/timeline
    env_file:
      - docker-hadoop/hadoop.env
    ports: 
      - "8188:8188"
  
  datanode1:
    image: bde2020/hadoop-datanode:1.1.0-hadoop2.7.1-java8
    container_name: datanode1
    depends_on:
      - namenode
    volumes:
      - /Docker/Volumes/Hdfs/datanode1:/hadoop/dfs/data
    env_file:
      - docker-hadoop/hadoop.env
    ports:
      - "50075:50075"

  flume: 
    image: apache-flume/ver:1.7
    container_name: flume
    ports:
      - "44444:44444"
    environment: 
       FLUME_CONF_DIR: /opt/flume/conf
       FLUME_AGENT_NAME: plotAgent
       FLUME_CONF_FILE: /opt/flume/conf/plot.conf 
    links:
      - kafka:kafka
      - namenode:namenode
