version: '2'
services:
  zookeeper:
    image: apache-zookeeper/ver:3.4.9
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
  cassandra:
    image: luketillman/datastax-enterprise:5.0.6
    ports:
      - "9042"
    volumes:
      - /Docker/Volumes/Cassandra:/var/lib/cassandra
      - /Docker/Volumes/Cassandra/Logs:/var/log/cassandra
  spark-master:
    image: bde2020/spark-master:2.0.0-hadoop2.7-hive-java8
    ports: 
      - "8080:8080"
      - "7077:7077"
    environment:
      ENABLE_INIT_DAEMON: "false"
  spark-slave:
    image: bde2020/spark-master:2.0.0-hadoop2.7-hive-java8
    ports: 
      - "8081:8080"
      - "7078:7077"
    environment:
      ENABLE_INIT_DAEMON: "false"
    links:
      - spark-master:spark-master
  kafka:
    image: apache-kafka/ver:0.10.0.2
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "vplusTopic:1:1:compact"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - zookeeper:zookeeper
      - cassandra:cassandra
      - spark-master
      - spark-slave
  flume: 
    image: apache-flume/ver:1.7
    ports:
      - "44444:44444"
    environment: 
       FLUME_CONF_DIR: /opt/flume/conf
       FLUME_AGENT_NAME: plotAgent
       FLUME_CONF_FILE: /opt/flume/conf/plot.conf 
    links:
      - kafka:kafka