version: "2"

services:
  namenode:
    image: bde2020/hadoop-namenode:1.1.0-hadoop2.7.1-java8
    container_name: namenode
    volumes:
      - /Docker/Volumes/Hdfs/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports: 
      - "50070:50070"
      - "8020:8020"
  resourcemanager:
    image: bde2020/hadoop-resourcemanager:1.1.0-hadoop2.7.1-java8
    container_name: resourcemanager
    depends_on:
      - namenode
      - datanode1
    env_file:
      - ./hadoop.env
    ports:
      - "8088:8088"
  
  historyserver:
    image: bde2020/hadoop-historyserver:1.1.0-hadoop2.7.1-java8
    container_name: historyserver
    depends_on:
      - namenode
      - datanode1
    volumes:
      - /Docker/Volumes/Hdfs/historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
    ports: 
      - "8188:8188"
  
  datanode1:
    image: bde2020/hadoop-datanode:1.1.0-hadoop2.7.1-java8
    container_name: datanode1
    depends_on:
      - namenode
    volumes:
      - /Docker/Volumes/Hdfs/datanode1:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    ports:
      - "50075:50075"

